[2024-09-08T17:13:17.905-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-08T17:13:17.911-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_dag.extract scheduled__2020-08-01T09:01:00+00:00 [queued]>
[2024-09-08T17:13:17.914-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_dag.extract scheduled__2020-08-01T09:01:00+00:00 [queued]>
[2024-09-08T17:13:17.914-0300] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-09-08T17:13:17.927-0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract> on 2020-08-01 09:01:00+00:00
[2024-09-08T17:13:17.934-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'spotify_dag', 'extract', 'scheduled__2020-08-01T09:01:00+00:00', '--job-id', '1139', '--raw', '--subdir', 'DAGS_FOLDER/spotify_dag.py', '--cfg-path', '/tmp/tmpey9c0oj5']
[2024-09-08T17:13:17.935-0300] {standard_task_runner.py:105} INFO - Job 1139: Subtask extract
[2024-09-08T17:13:17.936-0300] {logging_mixin.py:190} WARNING - /home/kasten/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=99376) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-08T17:13:17.937-0300] {standard_task_runner.py:72} INFO - Started process 99417 to run task
[2024-09-08T17:13:17.960-0300] {task_command.py:467} INFO - Running <TaskInstance: spotify_dag.extract scheduled__2020-08-01T09:01:00+00:00 [running]> on host kasten-Aspire-A315-54
[2024-09-08T17:13:18.006-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='gabriel.kasten@outlook.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='spotify_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2020-08-01T09:01:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-08-01T09:01:00+00:00'
[2024-09-08T17:13:18.007-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-08T17:13:18.007-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-08T17:13:18.007-0300] {logging_mixin.py:190} INFO - Current task name:extract state:running start_date:2024-09-08 20:13:17.911177+00:00
[2024-09-08T17:13:18.007-0300] {logging_mixin.py:190} INFO - Dag name:spotify_dag and current dag run status:running
[2024-09-08T17:13:18.007-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-08T17:13:18.300-0300] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/airflow/dags/steps/spotify_etl.py", line 70, in run_spotify_etl
    for song in data["items"]:
                ~~~~^^^^^^^^^
KeyError: 'items'
[2024-09-08T17:13:18.303-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-08T17:13:18.303-0300] {logging_mixin.py:190} INFO - Task start:2024-09-08 20:13:17.911177+00:00 end:2024-09-08 20:13:18.303281+00:00 duration:0.392104
[2024-09-08T17:13:18.303-0300] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract> dag:<DAG: spotify_dag> dagrun:<DagRun spotify_dag @ 2020-08-01 09:01:00+00:00: scheduled__2020-08-01T09:01:00+00:00, state:running, queued_at: 2024-09-08 20:12:11.852701+00:00. externally triggered: False>
[2024-09-08T17:13:18.304-0300] {logging_mixin.py:190} INFO - Failure caused by 'items'
[2024-09-08T17:13:18.304-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=spotify_dag, task_id=extract, run_id=scheduled__2020-08-01T09:01:00+00:00, execution_date=20200801T090100, start_date=20240908T201317, end_date=20240908T201318
[2024-09-08T17:13:18.316-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-08T17:13:18.316-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 1139 for task extract ('items'; 99417)
Traceback (most recent call last):
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/airflow/dags/steps/spotify_etl.py", line 70, in run_spotify_etl
    for song in data["items"]:
                ~~~~^^^^^^^^^
KeyError: 'items'
[2024-09-08T17:13:18.352-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-08T17:13:18.360-0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-08T17:13:18.360-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
